AWSTemplateFormatVersion: '2010-09-09'
Description: Create Glue Job and trigger it using Lambda

Resources:

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueJobExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaTriggerGlueRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueStartJobPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: my-sample-glue-job
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://your-script-bucket/scripts/sample_script.py
        PythonVersion: 3
      GlueVersion: "3.0"
      MaxCapacity: 2.0
      ExecutionProperty:
        MaxConcurrentRuns: 1

  GlueTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: trigger-glue-job
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 30
      Code:
        ZipFile: |
          import boto3
          def lambda_handler(event, context):
              client = boto3.client('glue')
              response = client.start_job_run(JobName='my-sample-glue-job')
              return response