AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket-name-mk # MUST be globally unique
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled